packages:
  - apps/*
  - packages/*

catalogs:
  cli:
    '@antfu/eslint-config': ^5.2.2
    '@antfu/ni': ^25.0.0
    '@changesets/cli': ^2.29.6
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/types': ^19.8.1
    '@eslint-react/eslint-plugin': ^1.53.0
    eslint: ^9.35.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    husky: ^9.1.7
    lint-staged: ^16.1.6
    tsx: ^4.20.5
    turbo: ^2.5.6
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.4
  inlined:
    '@antfu/utils': ^9.2.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.3.1
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
  ui:
    '@radix-ui/react-accordion': ^1.2.12
    '@radix-ui/react-alert-dialog': ^1.1.15
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.3
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-icons': ^1.3.2
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-switch': ^1.2.6
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-toast': ^1.2.15
    '@radix-ui/react-tooltip': ^1.2.8
    '@unocss/postcss': ^66.5.0
    '@unocss/preset-icons': ^66.5.0
    '@unocss/reset': ^66.5.0
    '@unocss/vite': ^66.5.0
    '@vitejs/plugin-react': ^5.0.2
    chalk: ^5.6.0
    class-variance-authority: ^0.7.1
    classic-level: ^3.0.0
    clsx: ^2.1.1
    commander: ^14.0.0
    enquirer: ^2.4.1
    ink: ^6.2.3
    lucide-react: ^0.542.0
    react: ^19.1.1
    react-dom: ^19.1.1
    simple-git: ^3.28.0
    tailwind-merge: ^3.3.1
    unocss: ^66.5.0
    unocss-preset-shadcn: ^1.0.1
  utils:
    defu: ^6.1.4
    i18next: ^25.5.2
    i18next-fs-backend: ^2.6.0
    pathe: ^2.0.3
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - classic-level
  - esbuild
